const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
const SIGN_UP_USER_FAILED = 'SIGN_UP_USER_FAILED';

const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';

export {
  SIGN_UP_USER_REQUEST,
  SIGN_UP_USER_SUCCESS,
  SIGN_UP_USER_FAILED,
  LOGIN_USER_REQUEST,
};
