const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
const SIGN_UP_USER_FAILED = 'SIGN_UP_USER_FAILED';

const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';

const UPDATE_USER_NAME_REQUEST = 'UPDATE_USER_NAME_REQUEST';
const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';

const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export {
  SIGN_UP_USER_REQUEST,
  SIGN_UP_USER_SUCCESS,
  SIGN_UP_USER_FAILED,
  LOGIN_USER_REQUEST,
  UPDATE_USER_NAME_REQUEST,
  UPDATE_PASSWORD_REQUEST,
  UPDATE_USER_REQUEST,
  LOGOUT_REQUEST,
};
